### ISSUE TITLE
Negative numbers not working

### ISSUE THREAD

**Issue by kazkis** [BlacKCaT27/CurrencyEditText#12]
Hi,
I'm trying to use your module but even though I'm including `app:allow_negative_values="true"` into my xml and the minus sign is shown on my keyboard, it won't allow me to insert negative numbers ( pressing it has no effect). Am I missing something?

PS: is it really necessary to include `InputType.TYPE_NUMBER_FLAG_DECIMAL`? Isn't the user supposed to insert only numbers?

**Comment by BlacKCaT27** [comment]
Hi there,

The negative sign feature is still very raw at the moment. It's quite picky and not as intuitive as I'd like it to be. I'll try to work on it this week.

Currently, you can only insert a negative if it's the first character that's input. once the formatter starts and numbers are in the field, the negative sign can't be added. I'm working on changing that though.

And you may be right about the decimal flag. I removed it and found no issues. I'll include that change in my patch.

Or if you'd like to submit a PR, I'll take a look as well.

**Comment by kazkis** [comment]
Thanks for your answer.
You are right: I was initializing my editText with some text inside it and that's why I had that problem. Leaving it empty for now is the only way to add a negative number.

I'm still quite new to the github system, so I think it's better for me to wait for your changes rather than risking making a mess :)

**Comment by BlacKCaT27** [comment]
Going to close this out as the negative feature works well enough for the odd use case which requires it (which I hope is not many). If there is additional desire for more robust negative support I'll consider adding it as a separate non-bug-fix feature
