### ISSUE TITLE
Ignore Decimal Values

### ISSUE THREAD

**Issue by janakaj** [BlacKCaT27/CurrencyEditText#16]
Is there a way to disable the decimal value? I only care about whole dollar amounts.

**Comment by BlacKCaT27** [comment]
Not currently, no. It wouldnt be difficult to add as an attribute, though.
If you care to take a stab at a PR I'll review it.

**Comment by LucasAzambuja42** [comment]
#17 (:

**Comment by BlacKCaT27** [comment]
Commented on your PR that this functionality is now available via the `setDecimalDigits()` method in v2.0. Closing this.
