### ISSUE TITLE
Indian localities/currencies Rupee support needed

### ISSUE THREAD

**Issue by LOG-TAG** [BlacKCaT27/CurrencyEditText#19]
This is the awesome library, but custom xml field will be awesome such that we can hard code the locale, also custom Unicode symbol / drawable   option will be grateful !

**Comment by BlacKCaT27** [comment]
Indian Rupee support is available in v2.0 of the library (at least on my test device running API 24, what locales are supported is device specific). 

I don't want to add an XML field for locale as they are a complex object not represented easily by simple values like ints and bools are. There's no type safety constructing objects via XML fields, and it's easy to accidentally construct a completely invalid locale object if you're not careful. Additionally, you wouldn't normally want to hard-code something like locale at the view level. Worst case, if you really want it to be set for only one locale, you can use `configureViewForLocale()` in java to do it. 

And as far as custom symbols go, you're free to call `setHint()` on the `CurrencyEditText` object just like any other `EditText` object. `setHint()` isn't overridden, it's just called on your behalf by default to show the currency symbol. But if you call it yourself, we cache your called value and honor that instead.
