### ISSUE TITLE
Poland currency issue

### ISSUE THREAD

**Issue by LucasEduardo** [BlacKCaT27/CurrencyEditText#20]
For Poland there is an issue because the currency simbol has 2 characters (for euro it is only 1). The code was coming from right to left 2 characters, the euro simbol and the space. I already fixed for my application and I'm going to do a pull request for this fix today.

**Comment by BlacKCaT27** [comment]
Thanks for looking into that! The code that's there now could definitely
use some polish (hah!). It was one of those "It works for now" pieces I
just haven't gotten back to. Looking forward to the pull request. Please
try to get a unit test or two around it as well, if you don't mind.

**Comment by BlacKCaT27** [comment]
I left you a note on your pull request but I'm adding it here as well:

Your proposed fix was great and I've included it in v2.0 of the library. I added the fix manually as I was right in the midst of a decently large refactoring and your fix was simple and straight-forward. I've credited you in the comments :)

**Comment by LucasEduardo** [comment]
That's great! Thank you! :)


*--*
*Lucas Eduardo*

2017-07-09 3:23 GMT-03:00 Josh Kitchens <notifications@github.com>:
