### ISSUE TITLE
Hİ, please help me with Turkish Liras 

### ISSUE THREAD

**Issue by clbemre** [BlacKCaT27/CurrencyEditText#22]
Unsupported ISO 4217 currency code: try (API 16)

**Comment by Themutlu** [comment]
I waiting for this.Turkish locale Unsupported

**Comment by BlacKCaT27** [comment]
Turkish locale works in v2.0 of the library (at least on my device running API 24). I don't have an easy way to test API 16 right this moment but give it a try.
