### ISSUE TITLE
SetText(CharSequence text) method passing empty string as parameter doesn't change mText

### ISSUE THREAD

**Issue by miguelfs** [BlacKCaT27/CurrencyEditText#24]
Hey! :)

I've had a problem: calling SetText("") to erase the displayed currency value and then bring the hint again doesn't work like default EditTexts.

I'm using CurrencyEditText inside my RecyclerView items. When I add a new item, I call SetText("") in my CurrencyEditText object to update it's value (for example, changing mText from "U$0,02" to "", so it would display back again the hint, like a default EditText), but it doesn't change the value.

Edit:
This situation happens inside the afterTextChanged(Editable editable) method of class CurrencyTextWatcher, when it tries to get a formatted text from an empty string:
![image](https://cloud.githubusercontent.com/assets/10662585/21193822/bd2b70d8-c214-11e6-803b-31c14687fe97.png)

I've converted initCurrencyTextWatcher() from private to public, and called it so It would be possible to reinitialize textWatcher field, and then lastGoodInput would be an empty string in this situation, but the app freezes in this situation.

Is there any way to force the hint to be displayed?

**Comment by rbiresch** [comment]
I created a PR that fixes this issue.

**Comment by BlacKCaT27** [comment]
Thanks for the PR! I'll try to take a look and merge it when I find some
time, which I'm sure you can understand is at a bit of a premium this time
of year.

Since I can't look at it ATM you may have already done this, but please
ensure unit tests are still passing and any new code has coverage.

Thanks!

**Comment by rbiresch** [comment]
You're welcome. This is a handy view you've created.

I found the tests and increased code coverage for the changes I've made.

**Comment by BlacKCaT27** [comment]
Fixed in v2.0.1
