### ISSUE TITLE
Setting currency doesn't change currency symbol

### ISSUE THREAD

**Issue by ebernie** [BlacKCaT27/CurrencyEditText#30]
Calling
`currencyFormatter.setCurrency(currency);`
in CurrencyTextFormatter seems to do the trick

**Comment by BlacKCaT27** [comment]
Version 2.0 was just released the other day, in which setCurrency was removed. Instead, you can set the hint symbol directly if you wish to override it. If you have a currency object, just set the hint to currency.getSymbol().

**Comment by neoscaler** [comment]
@BlacKCaT27  
If I set a explicit hint, for example because I always want to input $, regardless of the locale of the user, this gets reseted as soon as I enter a value in the field. Is it possible to set a fixed, persistent currency symbol?
