### ISSUE TITLE
force curser to right, when currecyEditText is focused

### ISSUE THREAD

**Issue by d34n0s** [BlacKCaT27/CurrencyEditText#32]
Hi, nice library, thank's for sharing it.
Do you know if it's possible to force the curser to the furthest right when the currencyEditText first gets focus?

As it is at the moment when the user clicks in the editText the curser just appears wherever they clicked, which means the first number they enter will appear at that position, then subsequent numbers will appear on the right. It makes the user experience a little awkward.

Cheers,

**Comment by BlacKCaT27** [comment]
Nice catch. I'll take a look tonight. Should be a simple fix.

**Comment by d34n0s** [comment]
i added the following to the CurrencyEditText class to solve the issue. Thanks, and please feel free to close this issue :)

    public void onSelectionChanged(int start, int end) {
        CharSequence text = getText();
        if (text != null) {
            if (start != text.length() || end != text.length()) {
                setSelection(text.length(), text.length());
                return;
            }
        }
        super.onSelectionChanged(start, end);
    }

**Comment by BlacKCaT27** [comment]
After trying this out as the library currently stands, I'm not sure I actually agree it's the correct behavior to ALWAYS force the cursor to the end. If you're editing an already populated field and just need to change, say, the 10s digit, it's easier to click in front of that, backspace once, enter in the new number, and be done, then to try to do so, have the cursor thrown to the right, hit backspace 3 times, enter the digit you wanted, reenter the digits that you had to delete (which you may have now forgotten), just to get to the same state. 

I'm going to close this issue since you've found a workaround for your use, but I'm not going to add this particular functionality to CET.

**Comment by d34n0s** [comment]
Yeah no problem at all. Thanks

What happens if the user deletes two characters in the middle of the string though, and then tries to replace both..... It get's a bit messy, as the first character will appear in the correct spot, then the second at far right.

It's a hard one to solve for all scenarios. I wish Android just had a currency control by default ;)

I'll stick to my forcing right I think just for consistent behaviour.

Thanks again for the lib :D

Great work!

P.S. I also modified it slightly so the user can toggle the value to and from a negative number at any time using the '-' key.

**Comment by BlacKCaT27** [comment]
"P.S. I also modified it slightly so the user can toggle the value to and
from a negative number at any time using the '-' key.".

Could you post that for me if you don't mind? That I very much would like
to add, I just hadn't gotten around to revamping negative value support yet.

**Comment by d34n0s** [comment]
This might not be the best way. But it's how I managed to get it working :)

1. first i had to create a KeyListener

`public class CurrencyKeyListener extends NumberKeyListener
{

    private static CurrencyKeyListener sInstance;

    @Override
    protected char[] getAcceptedChars() {
        return new char[] { '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '.' };
    }

    public static CurrencyKeyListener getInstance()
    {
        if(sInstance != null)
            return sInstance;
        sInstance = new CurrencyKeyListener();
        return sInstance;
    }

    public int getInputType()
    {
        return InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_FLAG_DECIMAL | InputType.TYPE_NUMBER_FLAG_SIGNED;
    }

}`

2. then make a couple of changes to the CurrencyEditText class.

a. in the init()

'this.setKeyListener(CurrencyKeyListener.getInstance());'

b. Add a method to change text colour (just a style preference, not really necessary)

`    protected void setNegativeTextColour(boolean b){

        if(b) {
            this.setTextColor(getResources().getColor(android.R.color.holo_red_light));
        } else {
            this.setTextColor(getResources().getColor(R.color.darkFont));
        }

    }`

3. modify the CurrencyTextWatcher classes After Text change to add a few lines.

`            newText = (editText.areNegativeValuesAllowed()) ? newText.replaceAll("[^0-9/-]", "") : newText.replaceAll("[^0-9]", "");

            //if newText already contains a '-' at the start and we receive another - at the end, remove the minus as the user wants to toggle
            if(newText.startsWith("-") && newText.endsWith("-")){
                newText = newText.replace("-","");
            }

            //move the incoming minus symbol from the back to the front
            if(newText.contains("-")){
                newText = newText.replace("-","");
                newText = newText.replace(newText, "-" + newText);
                editText.setNegativeTextColour(true);
            } else {
                editText.setNegativeTextColour(false);
            }


            if(!newText.equals("") && !newText.equals("-")){
                //Store a copy of the raw input to be retrieved later by getRawValue
                editText.setRawValue(Long.valueOf(newText));
            }`

**Comment by BlacKCaT27** [comment]
makes total sense. That's a great idea. If you want to submit a PR I'll
happily bring it in. Or if you'd rather I bake it in myself that's fine
too. Just let me know.

**Comment by d34n0s** [comment]
thanks josh, i don't have it cloned in git sorry. So can't submit PR.
