### ISSUE TITLE
Can not download

### ISSUE THREAD

**Issue by inromualdo** [BlacKCaT27/CurrencyEditText#33]
Error:(46, 13) Failed to resolve: com.github.BlacKCaT27:CurrencyEditText:v2.0.1

**Comment by BlacKCaT27** [comment]
My apologies, it looks like I neglected to update the maven repo with 2.0.1. I've just pushed an upload. Give it a few minutes from the time of this reply and try again. If it still doesn't work, you can try the jitpack repo instead. Either way, I'll be sure to get this pack up soon.

**Comment by kenshin171** [comment]
nop, unable to resolve form both jitpack and maven central

**Comment by BlacKCaT27** [comment]
Hrm...jitpack appears to be able to see the update, at least from their
website.

https://jitpack.io/#BlacKCaT27/CurrencyEditText/2.0.1

The instructions there don't get you a resolution?

I'll investigate further tonight, don't have access to what I need atm.

**Comment by kenshin171** [comment]
oh, i am able to resolve from jitpack now, the gradle dependency(for jitpack) version is 2.0.1 instead of v2.0.1. An update of the readme.md is in order i guess.

**Comment by BlacKCaT27** [comment]
Ah, my apologies then! I'll fix that. Thanks for the heads up!
