### ISSUE TITLE
Suggestion: Can you provide select box for user to change Locale himself?

### ISSUE THREAD

**Issue by inromualdo** [BlacKCaT27/CurrencyEditText#35]

**Comment by BlacKCaT27** [comment]
The only user facing part of this library is the CurrencyEditText box itself. Everything else is internal, so having a second user interface object would be difficult to manage at the library level.

That said, all the facilities are there in the library for you to do this yourself. Simply show a selection box of whichever locales you wish to support, then call setLocale() on the CurrencyEditText object to override the locale used.
