### ISSUE TITLE
Gradle Error: Failed to resolve: com.github.blackcat27:library:1.0.2-SNAPSHOT

### ISSUE THREAD

**Issue by phihos** [BlacKCaT27/CurrencyEditText#4]
Hi,

first of all, thank you for your work. You seem to be the only one, who made a simple currency EditText for Android. 

Your code does not seem to be available on maven central. I could also not find it by browsing through  http://search.maven.org/. So I guess your repository there might have been deleted for some reason. Could you fix this?

**Comment by BlacKCaT27** [comment]
Hi,
Yes, I wrote it.

I've been using it from maven with no issue. Please try with the latest
version (1.1.0). I may have forgotten to update the readme, and if so I'm
sorry about that.

I'll double check on to package in a bit. I'll admit I'm a bit green to
hosting code with maven, so it's very possible there's something I've
missed.

For now, please try the latest version and let me know if that helps.

-Josh

**Comment by BlacKCaT27** [comment]
Just double-checked the repo and it's definitely there.

**Comment by juliomarcos** [comment]
I was only able to use it after adding the following snippet to my app level build.gradle

repositories {
    mavenCentral()
    maven {
        url 'http://oss.sonatype.org/content/repositories/snapshots'
    }
}

**Comment by BlacKCaT27** [comment]
Closing issue as I haven't heard anymore on this and I'm able to use mavencentral with no issue. If anyone is still having problems please feel free to open another ticket. 

Also please check that you're using the latest version (1.1.2).
