### ISSUE TITLE
Symbol Visibility

### ISSUE THREAD

**Issue by Omid3d** [BlacKCaT27/CurrencyEditText#44]
Hi 

Is there any feature in the api to set visibility of currency symbol?
Actually my app gives user choice of currency selection, and based on this selected currency the price is formatted following corresponding symbol. 
This is not problem for US Dollar or Euro or even Yuan currencies to show symbol in CurrencyEditText, but for some locales this is not valid.
Consider for example user chooses Iranian's Rial, but on some devices this currency is not available, because there is no Persian locale by default in android. So my workaround is to not show currency symbol in edittext. But there is no option for that in CurrencyEditText!

Your library is great but I think that needs this feature.
Thanks

**Comment by BlacKCaT27** [comment]
Hello!

The currency symbol is simply default data which is filled in for the
EditText "hint" field. If you set the hint yourself, the currency symbol
will not appear.

In your case, you could hide the symbol by explicitly setting the symbol to
an empty string, out you could even populate the users selected currency
symbol by setting the hint to that.

Hope this helps

**Comment by Omid3d** [comment]
OK It seems I have to erase symbol manually. 

But anyway I think it would be better to provide an option for showing symbol or not.
Thanks for your support
