### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by mehmetyilmaz001** [BlacKCaT27/CurrencyEditText#5]
Hi,

I am new at gradle. 
I tried to add dependency to my gradle file as " compile 'com.github.blackcat27:library:1.2.0-SNAPSHOT'" and got error

Error:(33, 13) Failed to resolve: com.blackcat.currencyedittext:library:1.2.0-SNAPSHOT

What is the problem?

**Comment by BlacKCaT27** [comment]
Hello,
That should be all you need to do. Could you provide a little more information?

First, can you confirm which build.gradle file you inserted that line in? There are typically two; one for your overall project and one in the app folder. The compile line should go into the file in your app folder, not the main project folder file.

Thanks

**Comment by mehmetyilmaz001** [comment]
Hello,

Thank you for the fast response.

I put the depency line to my build.gradle file in the app folder. 

Here is a complete gist of gradle file in the app folder
https://gist.github.com/mehmetyilmaz001/50a67785f871d00de2f2

Gist of gradle file in the currencyedittext folder 
https://gist.github.com/mehmetyilmaz001/1cfa594631ede306feab

I commented the apply from line. When It is uncommented, I got the following error

"Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer"

**Comment by Harin-Kaklotar** [comment]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not resolve com.github.blackcat27:library:1.2.0-SNAPSHOT.
     Required by:
         ClientProject:app:unspecified
      > Could not resolve com.github.blackcat27:library:1.2.0-SNAPSHOT.
         > Could not get resource 'https://jitpack.io/com/github/blackcat27/library/1.2.0-SNAPSHOT/library-1.2.0-SNAPSHOT.pom'.
            > Could not GET 'https://jitpack.io/com/github/blackcat27/library/1.2.0-SNAPSHOT/library-1.2.0-SNAPSHOT.pom'. Received status code 401 from server: Repository not found or requires authentication
