### ISSUE TITLE
Problem with Locale.

### ISSUE THREAD

**Issue by doilio** [BlacKCaT27/CurrencyEditText#52]
So, my Locale displays well on the Edittext,
i save the value as Raw, but when I try to display the formatted Value.
it uses **US** Locale. how can I overcome this constraint?
```
        CurrencyEditText cet = new CurrencyEditText(context,null);
        String currentText = cet.formatCurrency(Long.toString(produtoActual.getValor()));
        Locale locale = new Locale("pt", "MZ");
        cet.setLocale(locale);
        viewHolder.preco.setText(currentText);
```

**Comment by BlacKCaT27** [comment]
Try setting the locale before calling formatCurrency

**Comment by doilio** [comment]
Worked Like a charm, Thanks for the fast reply.
Awesome Library
