### ISSUE TITLE
JitPack details in the README don't work

### ISSUE THREAD

**Issue by afollestad** [BlacKCaT27/CurrencyEditText#6]
I had to use this:

```Gradle
compile 'com.github.BlacKCaT27:CurrencyEditText:99064f2e2a'
```

**Comment by BlacKCaT27** [comment]
The readme didn't include any reference to JitPack until today when I added support for it by creating a github Release. That's why the version syntax of jitpack didn't work. It should work with JitPack now. I've updated the readme with the URL.
