### ISSUE TITLE
This library not work for me, it not give facility to enter number in edittext

### ISSUE THREAD

**Issue by Harin-Kaklotar** [BlacKCaT27/CurrencyEditText#7]

**Comment by BlacKCaT27** [comment]
Sorry it took so long to reply...

Could you clarify what you mean? What are you trying to do?

**Comment by BlacKCaT27** [comment]
Based solely on the title, it sounds like you're saying you want to set the number for the edittext field programmatically. 

To do this, you can take your raw value and use the formatCurrency method to get the formatted string, then set the CurrencyEditTexts text field directly with setText using the formatted string. 

I realize this isn't super straightforward; I'll look into adding a way to pass in a raw value when I have time.

**Comment by Harin-Kaklotar** [comment]
Ok thanks :)
