### ISSUE TITLE
Outdated version number in README

### ISSUE THREAD

**Issue by MarcinOrlowski** [BlacKCaT27/CurrencyEditText#9]
You should consider editing your README and replacing 

    compile 'com.github.BlacKCaT27:CurrencyEditText:v1.2.3'

with something more generic like

    compile 'com.github.BlacKCaT27:CurrencyEditText:v<VERSION>'

if you not plan to keep README updated after each release as others do that so people may simply copy this w/o checking into their gradle files and get hit by outdated version instead of recent one.

**Comment by BlacKCaT27** [comment]
Thanks for calling that out; I did update the readme with new feature information but missed updating the version number. It has now been updated.
